# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2q6TjUHN88QFksIkj8Ve3Hr18ZcKKWt
"""

import os

# Step 1. 현재 작업 디렉토리 확인
print("현재 작업 디렉토리:", os.getcwd())

# Step 2. 파일 생성
with open("sample.txt", "w", encoding="utf-8") as f:
    f.write("Hello, this is a test file.\n")
print("sample.txt 파일이 생성되었습니다.")

# Step 3. 상대 경로로 읽기
with open("sample.txt", "r", encoding="utf-8") as f:
    print("[상대 경로 읽기 결과]")
    print(f.read())

# Step 4. 절대 경로로 읽기
abs_path = os.path.abspath("sample.txt")
with open(abs_path, "r", encoding="utf-8") as f:
    print("[절대 경로 읽기 결과]")
    print(f.read())

# Step 5. 경로 비교 출력
print("상대 경로: sample.txt")
print("절대 경로:", abs_path)


# ------------------------------------------------
# 윈도우 환경 경로 문제 시뮬레이션
# ------------------------------------------------
print("\n[윈도우 환경 경로 문제 체험]")

# Step 6. 잘못된 예시 → SyntaxError 때문에 실행조차 안 됨
print("잘못된 예시: f = open(\"C:\\Users\\Guest\\test_path.txt\")")
print("→ SyntaxError 발생 (파이썬이 \\U 를 유니코드 이스케이프 시퀀스로 인식)")

# Step 7. 해결 방법 1: raw string 사용
try:
    f = open(r"C:\Users\Guest\test_path.txt", "r", encoding="utf-8")
    print("[raw string 읽기 결과]")
    print(f.read())
    f.close()
except Exception as e:
    print("[raw string 실행 오류]", e)

# Step 8. 해결 방법 2: 백슬래시 두 번 사용
try:
    f = open("C:\\Users\\Guest\\test_path.txt", "r", encoding="utf-8")
    print("[백슬래시 두 번 읽기 결과]")
    print(f.read())
    f.close()
except Exception as e:
    print("[백슬래시 두 번 실행 오류]", e)